#SUPPORT VECTOR MACHINES

###################Required Functions######################################
#This function tests whether a package has already been download
#and installed prior to attempting to do so.
EnsurePackage <- function(x)
{
  #Get copy of th package name.
  x <- as.character(x)
  
  if(!require(x, character.only = TRUE)){
    install.packages(pkgs = x, repos = "http://cran.r-project.org")
    require(x, character.only = TRUE)
  }
}
###########################################################################

#Include the SVM kernal lab  package.
EnsurePackage("kernlab")

#Get the built-in data set.
data("spam")

#Inspect the data set.
str(spam)

#Examine only the dimensions of the data set.
dim(spam)

#See the number of e-mails classified as spam and non-spam
#within the data set.
table(spam$type)

#Randomly divide the data set into two -- training and test set.
#1/3 for testing and 2/3 for testing.

#Create a random list of indexes to the spam e-mails.
randIndex <- sample(1:dim(spam)[1])

#Determine the 2/3 cut point.
cutPoint2_3 <- floor(2* dim(spam)[1]/3)

#Create the training data set.
trainData <- spam[randIndex[1:cutPoint2_3],]

#Create the test data set from the remaining data set.
testData <- spam[randIndex[(cutPoint2_3+1):dim(spam)[1]],]

#Generate a model based on training data set.
svmOutput <- ksvm(type ~., data = trainData, kernel = "rbfdot",
                  kpar = "automatic", C = 5, cross = 3,
                  prob.model = TRUE)

#View output.
svmOutput

#View results as a histogram.
hist(alpha(svmOutput)[[1]])

#Increase the cost parameter.
svmOutput <- ksvm(type ~., data = trainData, kernel = "rbfdot",
                  kpar = "automatic", C = 50, cross = 3,
                  prob.model = TRUE)

#View results as a histogram.
hist(alpha(svmOutput)[[1]],
     main = "Support Vector Histogram with C = 50",
     xlab = "Support Vector Values")

#Get indexes of items in the list that have small support vector values.
alphaindex(svmOutput)[[1]][alpha(svmOutput)[[1]] < 0.05]

#Examine one case.
trainData[90,]

#Get indexes of items in the list that have small support vector values.
alphaindex(svmOutput)[[1]][alpha(svmOutput)[[1]] == 50]

trainData[4,]

#Use the model to predict the test data.
svmPred <- predict(svmOutput, testData, type = "votes")

#Generate a confusion matrix to compare test data with
#data generated by the model.
compTable <- data.frame(testData[,58], svmPred[1,])

table(compTable)





